### ISSUE TITLE
No EXE File after Compiling?

### ISSUE THREAD

**Issue by hegyak** [SaxxonPike/roton#34]
I am using https://github.com/SaxxonPike/roton/commit/dd5f35f54b636d8cfc4a558daae51472e6416538
And after I compile the application on Windows, I can't seem to find an EXE File to run.

I am using Visual Studio Community 2017 15.7.5 on Windows 10.  I am unsure if my .Net Core is installed properly or not.  I don't get any error messages from Visual Studio when I build the solution.

**Comment by Spectere** [comment]
Hi hegyak,

By default, .NET Core only generates .DLL files when you perform a build. To run `Lyon.dll`, you can either use `dotnet Lyon.dll` from within the build directory or run it through Visual Studio.

To generate a standalone EXE you'll need to perform the following steps:

1. In Visual Studio, right-click on the Lyon project and click "Unload Project."
2. Right click "Lyon (unavailable)" and click "Edit Lyon.csproj."
3. Insert the following between the `<PropertyGroup>` element tags: `<RuntimeIdentifiers>win-x64</RuntimeIdentifiers>` (substitute `win-x64` with `win-x86` if you're running a 32-bit OS).
4. Close the editor tab.
5. Right-click on "Lyon (unavailable)" and click "Reload Project."
6. Next time you build the project, it will generate an EXE in `bin\{Debug/Release}\netcoreapp2.0\win-x64`.

Please note that you'll also have to grab an architecture-appropriate SDL2 runtime file from [libsdl.org](http://libsdl.org/download-2.0.php) in the same directory as Lyon in order to start the game.

Hope this helps!

**Comment by hegyak** [comment]
Here's what my Lyon.csproj looks like:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <OutputType>exe</OutputType>
    <LangVersion>latest</LangVersion>
    <StartupObject>Lyon.Program</StartupObject>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DotSDL\DotSDL\DotSDL.csproj" />
    <ProjectReference Include="..\Roton\Roton.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Autofac" Version="4.8.1" />
  </ItemGroup>
</Project>
```

However, I can't seem to find an EXE File still for Windows after making the changes, and doing a rebuild solution.

**Comment by SaxxonPike** [comment]
.NET Core does not build executables directly: https://stackoverflow.com/questions/44038847/vs2017-compile-netcoreapp-as-exe

Running the program requires the command line `dotnet lyon.dll`. We should really consider packaging a release that users can directly run. I'm leaving this issue open until we have something like this.

**Comment by Spectere** [comment]
Hey hegyak,

I had a chance to look into this on my Windows dev environment tonight and realized that I forgot a crucial step in the process: you have to right-click on the Lyon project, click publish, and step through the wizard (using the defaults will put it where I originally said it would be). That's what actually triggers the creation of the executable. After you do this once, the path will be stored.

I did a quick build of the latest `master`. You can find it here: [lyon-x64-34467b1c5.zip](https://files.spectere.net/projects/roton/lyon-x64-34467b1c5.zip).

**Comment by SaxxonPike** [comment]
We have, for the time being, added `Lyon.bat` and `lyon.sh` which should make it executable for now. Making executables from the get-go is only supported if we target a specific runtime, which we aren't doing. Lyon/Roton targets a *framework*. We will continue to explore options as .NET Core matures.

**Comment by hegyak** [comment]
Considering this resolved.  As having a way to launch Lyon that is user friend, is what I am really after here.
